### ISSUE TITLE
Impossible to get entity from Response inside a ResponseExceptionMapper when using kumuluzee-opentracing-jaeger version 1.3.1

### ISSUE THREAD

**Issue by caiquecastanho** [kumuluz/kumuluzee-opentracing#1]
When using the kumuluzee-opentracing-jaeger version 1.3.1 and implementing a ResponseExceptionMapper, the entity object inside the Response's object is null:

```
public class CurioExceptionMapper implements ResponseExceptionMapper<CurioNegocioException> {

@Override
    public CurioNegocioException toThrowable(Response response) {
        response.bufferEntity();
        try{
              response.readEntity(String.class); //here is impossible to get the entity
        }catch (Exception e){
            e.printStackTrace();
        }
    }

}
```
I'm using the Kumuluzee Microprofile Rest Client to make HTTP requests and I've done this code to throw an exception when the HTTP status code is different from 200, but when I try to inspect the response object it isn't possible to get the entity from response. If I change the version of opentracing-jaeger from 1.3.1 to 1.2.1 everything works fine.

**Comment by jmezna** [comment]
We will have a look and provide a fix shortly.

**Comment by jmezna** [comment]
We added a fix. Can you please build the latest SNAPSHOT and test if it fixes your problem. We will then prepare new patch release.
